### ISSUE TITLE
Jotunn update

### ISSUE THREAD

**Issue by C-Tripod** [shudnal/MoreGatesExtended#1]
Jotunn update yesterday getting error in log, starting at line 210 Gates aren't loading. don't know if its an easy fix or not, hope it is MoreGates is a staple in my playthroughs

![image](https://github.com/user-attachments/assets/3e499c37-c1e2-496c-83ba-b1e5c4459353)
[LogOutput.log](https://github.com/user-attachments/files/17467883/LogOutput.log)

**Comment by shudnal** [comment]
Jotunn 2.21.1 + More Gates Extended 1.0.1 works just fine on stable Valheim version. I was not able to break it.
Error has weird text. Added pieces should not have a PieceTable, it is a component of tools like hammer, hoe, cultivator.

**Comment by Stonearmdog** [comment]
I've also had the same issue. Thought it was an issue with the dedicated server, but my solo save is the same way.

EDIT: Disregard, shudnal. They just randomly came back. To OP the only thing I've done since is checked the integrity of game files for something else. Don't think that'd affect it, but that's the only difference the past couple days.

**Comment by shudnal** [comment]
What is in your config General -> Tool ?

**Comment by shudnal** [comment]
[MoreGatesExtended.zip](https://github.com/user-attachments/files/17479524/MoreGatesExtended.zip)
Pls check if that version still causes similar issue.

**Comment by shudnal** [comment]
Should be fixed in 1.0.2.
